// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: application.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HypergraphComparisonService_HyperStream_FullMethodName = "/quilibrium.node.application.pb.HypergraphComparisonService/HyperStream"
)

// HypergraphComparisonServiceClient is the client API for HypergraphComparisonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypergraphComparisonServiceClient interface {
	HyperStream(ctx context.Context, opts ...grpc.CallOption) (HypergraphComparisonService_HyperStreamClient, error)
}

type hypergraphComparisonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHypergraphComparisonServiceClient(cc grpc.ClientConnInterface) HypergraphComparisonServiceClient {
	return &hypergraphComparisonServiceClient{cc}
}

func (c *hypergraphComparisonServiceClient) HyperStream(ctx context.Context, opts ...grpc.CallOption) (HypergraphComparisonService_HyperStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &HypergraphComparisonService_ServiceDesc.Streams[0], HypergraphComparisonService_HyperStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &hypergraphComparisonServiceHyperStreamClient{stream}
	return x, nil
}

type HypergraphComparisonService_HyperStreamClient interface {
	Send(*HypergraphComparison) error
	Recv() (*HypergraphComparison, error)
	grpc.ClientStream
}

type hypergraphComparisonServiceHyperStreamClient struct {
	grpc.ClientStream
}

func (x *hypergraphComparisonServiceHyperStreamClient) Send(m *HypergraphComparison) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hypergraphComparisonServiceHyperStreamClient) Recv() (*HypergraphComparison, error) {
	m := new(HypergraphComparison)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HypergraphComparisonServiceServer is the server API for HypergraphComparisonService service.
// All implementations must embed UnimplementedHypergraphComparisonServiceServer
// for forward compatibility
type HypergraphComparisonServiceServer interface {
	HyperStream(HypergraphComparisonService_HyperStreamServer) error
	mustEmbedUnimplementedHypergraphComparisonServiceServer()
}

// UnimplementedHypergraphComparisonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHypergraphComparisonServiceServer struct {
}

func (UnimplementedHypergraphComparisonServiceServer) HyperStream(HypergraphComparisonService_HyperStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HyperStream not implemented")
}
func (UnimplementedHypergraphComparisonServiceServer) mustEmbedUnimplementedHypergraphComparisonServiceServer() {
}

// UnsafeHypergraphComparisonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypergraphComparisonServiceServer will
// result in compilation errors.
type UnsafeHypergraphComparisonServiceServer interface {
	mustEmbedUnimplementedHypergraphComparisonServiceServer()
}

func RegisterHypergraphComparisonServiceServer(s grpc.ServiceRegistrar, srv HypergraphComparisonServiceServer) {
	s.RegisterService(&HypergraphComparisonService_ServiceDesc, srv)
}

func _HypergraphComparisonService_HyperStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HypergraphComparisonServiceServer).HyperStream(&hypergraphComparisonServiceHyperStreamServer{stream})
}

type HypergraphComparisonService_HyperStreamServer interface {
	Send(*HypergraphComparison) error
	Recv() (*HypergraphComparison, error)
	grpc.ServerStream
}

type hypergraphComparisonServiceHyperStreamServer struct {
	grpc.ServerStream
}

func (x *hypergraphComparisonServiceHyperStreamServer) Send(m *HypergraphComparison) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hypergraphComparisonServiceHyperStreamServer) Recv() (*HypergraphComparison, error) {
	m := new(HypergraphComparison)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HypergraphComparisonService_ServiceDesc is the grpc.ServiceDesc for HypergraphComparisonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HypergraphComparisonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quilibrium.node.application.pb.HypergraphComparisonService",
	HandlerType: (*HypergraphComparisonServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HyperStream",
			Handler:       _HypergraphComparisonService_HyperStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "application.proto",
}
