// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.29.3
// source: application.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The HypergraphPhaseSet defines the specific phase set for further operation.
type HypergraphPhaseSet int32

const (
	HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_VERTEX_ADDS       HypergraphPhaseSet = 0
	HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_VERTEX_REMOVES    HypergraphPhaseSet = 1
	HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_HYPEREDGE_ADDS    HypergraphPhaseSet = 2
	HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_HYPEREDGE_REMOVES HypergraphPhaseSet = 3
)

// Enum value maps for HypergraphPhaseSet.
var (
	HypergraphPhaseSet_name = map[int32]string{
		0: "HYPERGRAPH_PHASE_SET_VERTEX_ADDS",
		1: "HYPERGRAPH_PHASE_SET_VERTEX_REMOVES",
		2: "HYPERGRAPH_PHASE_SET_HYPEREDGE_ADDS",
		3: "HYPERGRAPH_PHASE_SET_HYPEREDGE_REMOVES",
	}
	HypergraphPhaseSet_value = map[string]int32{
		"HYPERGRAPH_PHASE_SET_VERTEX_ADDS":       0,
		"HYPERGRAPH_PHASE_SET_VERTEX_REMOVES":    1,
		"HYPERGRAPH_PHASE_SET_HYPEREDGE_ADDS":    2,
		"HYPERGRAPH_PHASE_SET_HYPEREDGE_REMOVES": 3,
	}
)

func (x HypergraphPhaseSet) Enum() *HypergraphPhaseSet {
	p := new(HypergraphPhaseSet)
	*p = x
	return p
}

func (x HypergraphPhaseSet) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HypergraphPhaseSet) Descriptor() protoreflect.EnumDescriptor {
	return file_application_proto_enumTypes[0].Descriptor()
}

func (HypergraphPhaseSet) Type() protoreflect.EnumType {
	return &file_application_proto_enumTypes[0]
}

func (x HypergraphPhaseSet) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HypergraphPhaseSet.Descriptor instead.
func (HypergraphPhaseSet) EnumDescriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash    []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HypersyncMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaves         uint64 `protobuf:"varint,1,opt,name=leaves,proto3" json:"leaves,omitempty"`
	RootCommitment []byte `protobuf:"bytes,2,opt,name=root_commitment,json=rootCommitment,proto3" json:"root_commitment,omitempty"`
}

func (x *HypersyncMetadata) Reset() {
	*x = HypersyncMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypersyncMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypersyncMetadata) ProtoMessage() {}

func (x *HypersyncMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypersyncMetadata.ProtoReflect.Descriptor instead.
func (*HypersyncMetadata) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{1}
}

func (x *HypersyncMetadata) GetLeaves() uint64 {
	if x != nil {
		return x.Leaves
	}
	return 0
}

func (x *HypersyncMetadata) GetRootCommitment() []byte {
	if x != nil {
		return x.RootCommitment
	}
	return nil
}

// Defines the request for comparison of hypergraph data
type HypergraphComparisonQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The shard to compare.
	ShardKey []byte `protobuf:"bytes,1,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	// The phase set to compare.
	PhaseSet HypergraphPhaseSet `protobuf:"varint,2,opt,name=phase_set,json=phaseSet,proto3,enum=quilibrium.node.application.pb.HypergraphPhaseSet" json:"phase_set,omitempty"`
	// The branch path (sequence of nibble indices) in the vector commitment tree.
	Path []int32 `protobuf:"varint,3,rep,packed,name=path,proto3" json:"path,omitempty"`
	// The commitment for the node at this path.
	Commitment []byte `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// For branch nodes, a list of its immediate children (by index) and their
	// commitments. When the list is empty, it means either the node is a leaf or
	// no children diff info is needed.
	Children []*BranchChild `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	// If set, the comparison response will contain the data of leaves if present
	// in the results.
	IncludeLeafData bool `protobuf:"varint,6,opt,name=include_leaf_data,json=includeLeafData,proto3" json:"include_leaf_data,omitempty"`
}

func (x *HypergraphComparisonQuery) Reset() {
	*x = HypergraphComparisonQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphComparisonQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphComparisonQuery) ProtoMessage() {}

func (x *HypergraphComparisonQuery) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphComparisonQuery.ProtoReflect.Descriptor instead.
func (*HypergraphComparisonQuery) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{2}
}

func (x *HypergraphComparisonQuery) GetShardKey() []byte {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *HypergraphComparisonQuery) GetPhaseSet() HypergraphPhaseSet {
	if x != nil {
		return x.PhaseSet
	}
	return HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_VERTEX_ADDS
}

func (x *HypergraphComparisonQuery) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *HypergraphComparisonQuery) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *HypergraphComparisonQuery) GetChildren() []*BranchChild {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *HypergraphComparisonQuery) GetIncludeLeafData() bool {
	if x != nil {
		return x.IncludeLeafData
	}
	return false
}

// Defines the response containing the commitment for a node and (optionally)
// its immediate children. The children are identified by their index (0–63) and
// their commitments.
type HypergraphComparisonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The branch path for this node.
	Path []int32 `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	// The commitment for the node at this path.
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// If non-empty, a list of children for which the node can report commitments.
	// (For instance, if the node is a branch you may want to send the commitment
	// for each child.)
	Children []*BranchChild `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	// If set, indicates the response is for the root of the given set tree.
	IsRoot bool `protobuf:"varint,4,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
}

func (x *HypergraphComparisonResponse) Reset() {
	*x = HypergraphComparisonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphComparisonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphComparisonResponse) ProtoMessage() {}

func (x *HypergraphComparisonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphComparisonResponse.ProtoReflect.Descriptor instead.
func (*HypergraphComparisonResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{3}
}

func (x *HypergraphComparisonResponse) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *HypergraphComparisonResponse) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *HypergraphComparisonResponse) GetChildren() []*BranchChild {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *HypergraphComparisonResponse) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

// Defines the child commitment.
type BranchChild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The index on the branch's children.
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The commitment of the data.
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *BranchChild) Reset() {
	*x = BranchChild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchChild) ProtoMessage() {}

func (x *BranchChild) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchChild.ProtoReflect.Descriptor instead.
func (*BranchChild) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{4}
}

func (x *BranchChild) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BranchChild) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

// Defines the data of the leaf.
type LeafData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The full key of the leaf.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value for the leaf.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The hash target if any.
	HashTarget []byte `protobuf:"bytes,3,opt,name=hash_target,json=hashTarget,proto3" json:"hash_target,omitempty"`
	// The size, represented as big endian unsigned bytes.
	Size []byte `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	// The underlying data backing the leaf, if a vertex.
	UnderlyingData []byte `protobuf:"bytes,5,opt,name=underlying_data,json=underlyingData,proto3" json:"underlying_data,omitempty"`
}

func (x *LeafData) Reset() {
	*x = LeafData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafData) ProtoMessage() {}

func (x *LeafData) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafData.ProtoReflect.Descriptor instead.
func (*LeafData) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{5}
}

func (x *LeafData) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LeafData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LeafData) GetHashTarget() []byte {
	if x != nil {
		return x.HashTarget
	}
	return nil
}

func (x *LeafData) GetSize() []byte {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *LeafData) GetUnderlyingData() []byte {
	if x != nil {
		return x.UnderlyingData
	}
	return nil
}

// Defines the bidirectional sync payload options.
type HypergraphComparison struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*HypergraphComparison_Query
	//	*HypergraphComparison_Response
	//	*HypergraphComparison_LeafData
	//	*HypergraphComparison_Metadata
	Payload isHypergraphComparison_Payload `protobuf_oneof:"payload"`
}

func (x *HypergraphComparison) Reset() {
	*x = HypergraphComparison{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HypergraphComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypergraphComparison) ProtoMessage() {}

func (x *HypergraphComparison) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypergraphComparison.ProtoReflect.Descriptor instead.
func (*HypergraphComparison) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{6}
}

func (m *HypergraphComparison) GetPayload() isHypergraphComparison_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *HypergraphComparison) GetQuery() *HypergraphComparisonQuery {
	if x, ok := x.GetPayload().(*HypergraphComparison_Query); ok {
		return x.Query
	}
	return nil
}

func (x *HypergraphComparison) GetResponse() *HypergraphComparisonResponse {
	if x, ok := x.GetPayload().(*HypergraphComparison_Response); ok {
		return x.Response
	}
	return nil
}

func (x *HypergraphComparison) GetLeafData() *LeafData {
	if x, ok := x.GetPayload().(*HypergraphComparison_LeafData); ok {
		return x.LeafData
	}
	return nil
}

func (x *HypergraphComparison) GetMetadata() *HypersyncMetadata {
	if x, ok := x.GetPayload().(*HypergraphComparison_Metadata); ok {
		return x.Metadata
	}
	return nil
}

type isHypergraphComparison_Payload interface {
	isHypergraphComparison_Payload()
}

type HypergraphComparison_Query struct {
	Query *HypergraphComparisonQuery `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type HypergraphComparison_Response struct {
	Response *HypergraphComparisonResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type HypergraphComparison_LeafData struct {
	LeafData *LeafData `protobuf:"bytes,3,opt,name=leaf_data,json=leafData,proto3,oneof"`
}

type HypergraphComparison_Metadata struct {
	Metadata *HypersyncMetadata `protobuf:"bytes,4,opt,name=metadata,proto3,oneof"`
}

func (*HypergraphComparison_Query) isHypergraphComparison_Payload() {}

func (*HypergraphComparison_Response) isHypergraphComparison_Payload() {}

func (*HypergraphComparison_LeafData) isHypergraphComparison_Payload() {}

func (*HypergraphComparison_Metadata) isHypergraphComparison_Payload() {}

// Multiproof contains the cryptographic proof data
type Multiproof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multicommitment []byte `protobuf:"bytes,1,opt,name=multicommitment,proto3" json:"multicommitment,omitempty"`
	Proof           []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *Multiproof) Reset() {
	*x = Multiproof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Multiproof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Multiproof) ProtoMessage() {}

func (x *Multiproof) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Multiproof.ProtoReflect.Descriptor instead.
func (*Multiproof) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{7}
}

func (x *Multiproof) GetMulticommitment() []byte {
	if x != nil {
		return x.Multicommitment
	}
	return nil
}

func (x *Multiproof) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// Path represents a sequence of indices through the tree
type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indices []uint64 `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{8}
}

func (x *Path) GetIndices() []uint64 {
	if x != nil {
		return x.Indices
	}
	return nil
}

// TraversalSubProof contains proof data for a single path traversal
type TraversalSubProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commits [][]byte `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	Ys      [][]byte `protobuf:"bytes,2,rep,name=ys,proto3" json:"ys,omitempty"`
	Paths   []*Path  `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *TraversalSubProof) Reset() {
	*x = TraversalSubProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraversalSubProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraversalSubProof) ProtoMessage() {}

func (x *TraversalSubProof) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraversalSubProof.ProtoReflect.Descriptor instead.
func (*TraversalSubProof) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{9}
}

func (x *TraversalSubProof) GetCommits() [][]byte {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *TraversalSubProof) GetYs() [][]byte {
	if x != nil {
		return x.Ys
	}
	return nil
}

func (x *TraversalSubProof) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

// TraversalProof is the main proof structure for tree traversals
type TraversalProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiproof *Multiproof          `protobuf:"bytes,1,opt,name=multiproof,proto3" json:"multiproof,omitempty"`
	SubProofs  []*TraversalSubProof `protobuf:"bytes,2,rep,name=sub_proofs,json=subProofs,proto3" json:"sub_proofs,omitempty"`
}

func (x *TraversalProof) Reset() {
	*x = TraversalProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraversalProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraversalProof) ProtoMessage() {}

func (x *TraversalProof) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraversalProof.ProtoReflect.Descriptor instead.
func (*TraversalProof) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{10}
}

func (x *TraversalProof) GetMultiproof() *Multiproof {
	if x != nil {
		return x.Multiproof
	}
	return nil
}

func (x *TraversalProof) GetSubProofs() []*TraversalSubProof {
	if x != nil {
		return x.SubProofs
	}
	return nil
}

type GetChildrenForPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The shard key
	ShardKey []byte `protobuf:"bytes,1,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	// The path to request
	Path []uint32 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	// The phase set to compare.
	PhaseSet HypergraphPhaseSet `protobuf:"varint,3,opt,name=phase_set,json=phaseSet,proto3,enum=quilibrium.node.application.pb.HypergraphPhaseSet" json:"phase_set,omitempty"`
}

func (x *GetChildrenForPathRequest) Reset() {
	*x = GetChildrenForPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChildrenForPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildrenForPathRequest) ProtoMessage() {}

func (x *GetChildrenForPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildrenForPathRequest.ProtoReflect.Descriptor instead.
func (*GetChildrenForPathRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{11}
}

func (x *GetChildrenForPathRequest) GetShardKey() []byte {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *GetChildrenForPathRequest) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *GetChildrenForPathRequest) GetPhaseSet() HypergraphPhaseSet {
	if x != nil {
		return x.PhaseSet
	}
	return HypergraphPhaseSet_HYPERGRAPH_PHASE_SET_VERTEX_ADDS
}

type TreePathLeaf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key associated with the leaf
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The raw value associated with the leaf
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The hash target of the leaf, if applicable
	HashTarget []byte `protobuf:"bytes,3,opt,name=hash_target,json=hashTarget,proto3" json:"hash_target,omitempty"`
	// The commitment of the leaf
	Commitment []byte `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// The big endian encoded size of the leaf
	Size []byte `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *TreePathLeaf) Reset() {
	*x = TreePathLeaf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreePathLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePathLeaf) ProtoMessage() {}

func (x *TreePathLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePathLeaf.ProtoReflect.Descriptor instead.
func (*TreePathLeaf) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{12}
}

func (x *TreePathLeaf) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TreePathLeaf) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TreePathLeaf) GetHashTarget() []byte {
	if x != nil {
		return x.HashTarget
	}
	return nil
}

func (x *TreePathLeaf) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *TreePathLeaf) GetSize() []byte {
	if x != nil {
		return x.Size
	}
	return nil
}

type TreePathBranch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The prefix segment of the branch that exists only within the branch
	Prefix []uint32 `protobuf:"varint,1,rep,packed,name=prefix,proto3" json:"prefix,omitempty"`
	// The commitment of the branch
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// The big endian encoded size of the branch
	Size []byte `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	// The number of leaves under the branch
	LeafCount uint64 `protobuf:"varint,4,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"`
	// The longest branch length under the branch
	LongestBranch uint32 `protobuf:"varint,5,opt,name=longest_branch,json=longestBranch,proto3" json:"longest_branch,omitempty"`
	// The full path prefix to the branch
	FullPrefix []uint32 `protobuf:"varint,6,rep,packed,name=full_prefix,json=fullPrefix,proto3" json:"full_prefix,omitempty"`
}

func (x *TreePathBranch) Reset() {
	*x = TreePathBranch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreePathBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePathBranch) ProtoMessage() {}

func (x *TreePathBranch) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePathBranch.ProtoReflect.Descriptor instead.
func (*TreePathBranch) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{13}
}

func (x *TreePathBranch) GetPrefix() []uint32 {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *TreePathBranch) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *TreePathBranch) GetSize() []byte {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *TreePathBranch) GetLeafCount() uint64 {
	if x != nil {
		return x.LeafCount
	}
	return 0
}

func (x *TreePathBranch) GetLongestBranch() uint32 {
	if x != nil {
		return x.LongestBranch
	}
	return 0
}

func (x *TreePathBranch) GetFullPrefix() []uint32 {
	if x != nil {
		return x.FullPrefix
	}
	return nil
}

type TreePathSegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are assignable to Segment:
	//
	//	*TreePathSegment_Leaf
	//	*TreePathSegment_Branch
	Segment isTreePathSegment_Segment `protobuf_oneof:"segment"`
}

func (x *TreePathSegment) Reset() {
	*x = TreePathSegment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreePathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePathSegment) ProtoMessage() {}

func (x *TreePathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePathSegment.ProtoReflect.Descriptor instead.
func (*TreePathSegment) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{14}
}

func (x *TreePathSegment) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (m *TreePathSegment) GetSegment() isTreePathSegment_Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

func (x *TreePathSegment) GetLeaf() *TreePathLeaf {
	if x, ok := x.GetSegment().(*TreePathSegment_Leaf); ok {
		return x.Leaf
	}
	return nil
}

func (x *TreePathSegment) GetBranch() *TreePathBranch {
	if x, ok := x.GetSegment().(*TreePathSegment_Branch); ok {
		return x.Branch
	}
	return nil
}

type isTreePathSegment_Segment interface {
	isTreePathSegment_Segment()
}

type TreePathSegment_Leaf struct {
	Leaf *TreePathLeaf `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

type TreePathSegment_Branch struct {
	Branch *TreePathBranch `protobuf:"bytes,3,opt,name=branch,proto3,oneof"`
}

func (*TreePathSegment_Leaf) isTreePathSegment_Segment() {}

func (*TreePathSegment_Branch) isTreePathSegment_Segment() {}

type TreePathSegments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []*TreePathSegment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *TreePathSegments) Reset() {
	*x = TreePathSegments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreePathSegments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreePathSegments) ProtoMessage() {}

func (x *TreePathSegments) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreePathSegments.ProtoReflect.Descriptor instead.
func (*TreePathSegments) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{15}
}

func (x *TreePathSegments) GetSegments() []*TreePathSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type GetChildrenForPathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathSegments []*TreePathSegments `protobuf:"bytes,1,rep,name=path_segments,json=pathSegments,proto3" json:"path_segments,omitempty"`
}

func (x *GetChildrenForPathResponse) Reset() {
	*x = GetChildrenForPathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChildrenForPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildrenForPathResponse) ProtoMessage() {}

func (x *GetChildrenForPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildrenForPathResponse.ProtoReflect.Descriptor instead.
func (*GetChildrenForPathResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{16}
}

func (x *GetChildrenForPathResponse) GetPathSegments() []*TreePathSegments {
	if x != nil {
		return x.PathSegments
	}
	return nil
}

var File_application_proto protoreflect.FileDescriptor

var file_application_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x62, 0x22, 0x51, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x54, 0x0a, 0x11, 0x48, 0x79, 0x70, 0x65, 0x72, 0x73,
	0x79, 0x6e, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x61, 0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x72, 0x6f,
	0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xb2, 0x02, 0x0a,
	0x19, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x69, 0x73, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x4f, 0x0a, 0x09, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x71, 0x75, 0x69,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70, 0x65,
	0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x65, 0x74, 0x52, 0x08,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x53, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x08,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x5f, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x4c, 0x65, 0x61, 0x66, 0x44, 0x61, 0x74,
	0x61, 0x22, 0xb4, 0x01, 0x0a, 0x1c, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69,
	0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x90, 0x01,
	0x0a, 0x08, 0x4c, 0x65, 0x61, 0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x75, 0x6e, 0x64, 0x65, 0x72,
	0x6c, 0x79, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x22, 0xea, 0x02, 0x0a, 0x14, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69,
	0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x5a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c,
	0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x69, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x66,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61,
	0x66, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x66, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x4f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x73, 0x79, 0x6e, 0x63, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4c, 0x0a,
	0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x28, 0x0a, 0x0f, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x20, 0x0a, 0x04, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22, 0x79, 0x0a,
	0x11, 0x54, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x79, 0x73, 0x12, 0x3a, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x4a, 0x0a, 0x0a, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x0a, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x50, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x53, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x09,
	0x73, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x4f, 0x0a, 0x09, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70,
	0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x65, 0x74, 0x52,
	0x08, 0x70, 0x68, 0x61, 0x73, 0x65, 0x53, 0x65, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x54, 0x72,
	0x65, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x65, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x66,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x5f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c,
	0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xc0, 0x01,
	0x0a, 0x0f, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x42, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69,
	0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c,
	0x65, 0x61, 0x66, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x12, 0x48, 0x0a, 0x06, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x48, 0x00, 0x52, 0x06, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x42, 0x09, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x5f, 0x0a, 0x10, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72,
	0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x73, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x46, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x55, 0x0a, 0x0d, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72,
	0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x70, 0x61, 0x74, 0x68, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2a, 0xb8, 0x01, 0x0a, 0x12, 0x48, 0x79, 0x70, 0x65, 0x72,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x65, 0x74, 0x12, 0x24, 0x0a,
	0x20, 0x48, 0x59, 0x50, 0x45, 0x52, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x50, 0x48, 0x41, 0x53,
	0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x56, 0x45, 0x52, 0x54, 0x45, 0x58, 0x5f, 0x41, 0x44, 0x44,
	0x53, 0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x48, 0x59, 0x50, 0x45, 0x52, 0x47, 0x52, 0x41, 0x50,
	0x48, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x56, 0x45, 0x52, 0x54,
	0x45, 0x58, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x53, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23,
	0x48, 0x59, 0x50, 0x45, 0x52, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45,
	0x5f, 0x53, 0x45, 0x54, 0x5f, 0x48, 0x59, 0x50, 0x45, 0x52, 0x45, 0x44, 0x47, 0x45, 0x5f, 0x41,
	0x44, 0x44, 0x53, 0x10, 0x02, 0x12, 0x2a, 0x0a, 0x26, 0x48, 0x59, 0x50, 0x45, 0x52, 0x47, 0x52,
	0x41, 0x50, 0x48, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x48, 0x59,
	0x50, 0x45, 0x52, 0x45, 0x44, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x53, 0x10,
	0x03, 0x32, 0xaa, 0x02, 0x0a, 0x1b, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x7d, 0x0a, 0x0b, 0x48, 0x79, 0x70, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x34, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61, 0x70, 0x68, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x1a, 0x34, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72,
	0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x8b, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x46, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x39, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62,
	0x72, 0x69, 0x75, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x75, 0x6d, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x46,
	0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a,
	0x5a, 0x38, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72,
	0x69, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x69, 0x6c, 0x69, 0x62, 0x72, 0x69,
	0x75, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_application_proto_rawDescOnce sync.Once
	file_application_proto_rawDescData = file_application_proto_rawDesc
)

func file_application_proto_rawDescGZIP() []byte {
	file_application_proto_rawDescOnce.Do(func() {
		file_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_application_proto_rawDescData)
	})
	return file_application_proto_rawDescData
}

var file_application_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_application_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_application_proto_goTypes = []interface{}{
	(HypergraphPhaseSet)(0),              // 0: quilibrium.node.application.pb.HypergraphPhaseSet
	(*Message)(nil),                      // 1: quilibrium.node.application.pb.Message
	(*HypersyncMetadata)(nil),            // 2: quilibrium.node.application.pb.HypersyncMetadata
	(*HypergraphComparisonQuery)(nil),    // 3: quilibrium.node.application.pb.HypergraphComparisonQuery
	(*HypergraphComparisonResponse)(nil), // 4: quilibrium.node.application.pb.HypergraphComparisonResponse
	(*BranchChild)(nil),                  // 5: quilibrium.node.application.pb.BranchChild
	(*LeafData)(nil),                     // 6: quilibrium.node.application.pb.LeafData
	(*HypergraphComparison)(nil),         // 7: quilibrium.node.application.pb.HypergraphComparison
	(*Multiproof)(nil),                   // 8: quilibrium.node.application.pb.Multiproof
	(*Path)(nil),                         // 9: quilibrium.node.application.pb.Path
	(*TraversalSubProof)(nil),            // 10: quilibrium.node.application.pb.TraversalSubProof
	(*TraversalProof)(nil),               // 11: quilibrium.node.application.pb.TraversalProof
	(*GetChildrenForPathRequest)(nil),    // 12: quilibrium.node.application.pb.GetChildrenForPathRequest
	(*TreePathLeaf)(nil),                 // 13: quilibrium.node.application.pb.TreePathLeaf
	(*TreePathBranch)(nil),               // 14: quilibrium.node.application.pb.TreePathBranch
	(*TreePathSegment)(nil),              // 15: quilibrium.node.application.pb.TreePathSegment
	(*TreePathSegments)(nil),             // 16: quilibrium.node.application.pb.TreePathSegments
	(*GetChildrenForPathResponse)(nil),   // 17: quilibrium.node.application.pb.GetChildrenForPathResponse
}
var file_application_proto_depIdxs = []int32{
	0,  // 0: quilibrium.node.application.pb.HypergraphComparisonQuery.phase_set:type_name -> quilibrium.node.application.pb.HypergraphPhaseSet
	5,  // 1: quilibrium.node.application.pb.HypergraphComparisonQuery.children:type_name -> quilibrium.node.application.pb.BranchChild
	5,  // 2: quilibrium.node.application.pb.HypergraphComparisonResponse.children:type_name -> quilibrium.node.application.pb.BranchChild
	3,  // 3: quilibrium.node.application.pb.HypergraphComparison.query:type_name -> quilibrium.node.application.pb.HypergraphComparisonQuery
	4,  // 4: quilibrium.node.application.pb.HypergraphComparison.response:type_name -> quilibrium.node.application.pb.HypergraphComparisonResponse
	6,  // 5: quilibrium.node.application.pb.HypergraphComparison.leaf_data:type_name -> quilibrium.node.application.pb.LeafData
	2,  // 6: quilibrium.node.application.pb.HypergraphComparison.metadata:type_name -> quilibrium.node.application.pb.HypersyncMetadata
	9,  // 7: quilibrium.node.application.pb.TraversalSubProof.paths:type_name -> quilibrium.node.application.pb.Path
	8,  // 8: quilibrium.node.application.pb.TraversalProof.multiproof:type_name -> quilibrium.node.application.pb.Multiproof
	10, // 9: quilibrium.node.application.pb.TraversalProof.sub_proofs:type_name -> quilibrium.node.application.pb.TraversalSubProof
	0,  // 10: quilibrium.node.application.pb.GetChildrenForPathRequest.phase_set:type_name -> quilibrium.node.application.pb.HypergraphPhaseSet
	13, // 11: quilibrium.node.application.pb.TreePathSegment.leaf:type_name -> quilibrium.node.application.pb.TreePathLeaf
	14, // 12: quilibrium.node.application.pb.TreePathSegment.branch:type_name -> quilibrium.node.application.pb.TreePathBranch
	15, // 13: quilibrium.node.application.pb.TreePathSegments.segments:type_name -> quilibrium.node.application.pb.TreePathSegment
	16, // 14: quilibrium.node.application.pb.GetChildrenForPathResponse.path_segments:type_name -> quilibrium.node.application.pb.TreePathSegments
	7,  // 15: quilibrium.node.application.pb.HypergraphComparisonService.HyperStream:input_type -> quilibrium.node.application.pb.HypergraphComparison
	12, // 16: quilibrium.node.application.pb.HypergraphComparisonService.GetChildrenForPath:input_type -> quilibrium.node.application.pb.GetChildrenForPathRequest
	7,  // 17: quilibrium.node.application.pb.HypergraphComparisonService.HyperStream:output_type -> quilibrium.node.application.pb.HypergraphComparison
	17, // 18: quilibrium.node.application.pb.HypergraphComparisonService.GetChildrenForPath:output_type -> quilibrium.node.application.pb.GetChildrenForPathResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_application_proto_init() }
func file_application_proto_init() {
	if File_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypersyncMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphComparisonQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphComparisonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchChild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HypergraphComparison); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Multiproof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraversalSubProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraversalProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChildrenForPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreePathLeaf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreePathBranch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreePathSegment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreePathSegments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChildrenForPathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_application_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*HypergraphComparison_Query)(nil),
		(*HypergraphComparison_Response)(nil),
		(*HypergraphComparison_LeafData)(nil),
		(*HypergraphComparison_Metadata)(nil),
	}
	file_application_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*TreePathSegment_Leaf)(nil),
		(*TreePathSegment_Branch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_application_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_proto_goTypes,
		DependencyIndexes: file_application_proto_depIdxs,
		EnumInfos:         file_application_proto_enumTypes,
		MessageInfos:      file_application_proto_msgTypes,
	}.Build()
	File_application_proto = out.File
	file_application_proto_rawDesc = nil
	file_application_proto_goTypes = nil
	file_application_proto_depIdxs = nil
}
